package net.haro0.hytale.graveprotocol.ui;

import com.hypixel.hytale.builtin.instances.InstancesPlugin;
import com.hypixel.hytale.codec.Codec;
import com.hypixel.hytale.codec.KeyedCodec;
import com.hypixel.hytale.codec.builder.BuilderCodec;
import com.hypixel.hytale.component.Ref;
import com.hypixel.hytale.component.Store;
import com.hypixel.hytale.math.vector.Transform;
import com.hypixel.hytale.math.vector.Vector3f;
import com.hypixel.hytale.protocol.packets.interface_.CustomPageLifetime;
import com.hypixel.hytale.protocol.packets.interface_.CustomUIEventBindingType;
import com.hypixel.hytale.server.core.entity.entities.Player;
import com.hypixel.hytale.server.core.entity.entities.player.pages.InteractiveCustomUIPage;
import com.hypixel.hytale.server.core.inventory.ItemStack;
import com.hypixel.hytale.server.core.modules.entity.component.TransformComponent;
import com.hypixel.hytale.server.core.modules.entity.damage.DeathComponent;
import com.hypixel.hytale.server.core.ui.builder.EventData;
import com.hypixel.hytale.server.core.ui.builder.UICommandBuilder;
import com.hypixel.hytale.server.core.ui.builder.UIEventBuilder;
import com.hypixel.hytale.server.core.universe.PlayerRef;
import com.hypixel.hytale.server.core.universe.world.World;
import com.hypixel.hytale.server.core.universe.world.storage.EntityStore;
import net.haro0.hytale.graveprotocol.components.GraveProtocolComponent;

import javax.annotation.Nonnull;
import java.util.concurrent.CompletableFuture;

// Generated by Hytale UI Builder (https://hytale.ellie.au).
// You may edit this class as necessary, or copy parts only.
public class DeathDecisionUi extends InteractiveCustomUIPage<DeathDecisionUi.BindingData> {

    public DeathDecisionUi(@Nonnull PlayerRef playerRef) {

        super(playerRef, CustomPageLifetime.CantClose, BindingData.CODEC);
    }

    @Override
    public void build(@Nonnull Ref<EntityStore> ref, @Nonnull UICommandBuilder uiCommandBuilder, @Nonnull UIEventBuilder uiEventBuilder, @Nonnull Store<EntityStore> store) {

        uiCommandBuilder.append("Pages/DeathDecision.ui");

        uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#Normal", EventData.of("Action", "Normal"));
        uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#Custom", EventData.of("Action", "Custom"));

        // var config = MyPlugin.getInstance().config.get();

    }

    @Override
    public void handleDataEvent(@Nonnull Ref<EntityStore> ref, @Nonnull Store<EntityStore> store, @Nonnull BindingData data) {

        var player = store.getComponent(ref, Player.getComponentType());
        assert player != null;
        var decisionComponent = store.getComponent(ref, GraveProtocolComponent.getComponentType());
        assert decisionComponent != null;
        switch (data.action) {
            case "Normal" -> {
                store.putComponent(ref, DeathComponent.getComponentType(), decisionComponent.getOriginal());
            }
            case "Custom" -> {
                var transformComponent = store.getComponent(ref, TransformComponent.getComponentType());
                assert transformComponent != null;
                var world = player.getWorld();
                assert world != null;
                world.execute(() -> {
                    decisionComponent.setItems(player.getInventory().getCombinedEverything().removeAllItemStacks().toArray(ItemStack[]::new));
                    player.markNeedsSave();
                    CompletableFuture<World> worldFuture = InstancesPlugin.get().spawnInstance("Grave_Protocol_1", world, new Transform(transformComponent.getPosition().clone(), Vector3f.FORWARD));
                    InstancesPlugin.teleportPlayerToLoadingInstance(playerRef.getReference(), playerRef.getReference().getStore(), worldFuture, null);
                });
                close();
            }
        }

    }

    public static class BindingData {

        public static final BuilderCodec<BindingData> CODEC = BuilderCodec.builder(BindingData.class, BindingData::new)
            .append(new KeyedCodec<>("Action", Codec.STRING), (entry, s) -> entry.action = s, entry -> entry.action).add()
            .build();

        private String action;

    }

}
