package net.haro0.hytale.graveprotocol.ui;

import com.hypixel.hytale.codec.Codec;
import com.hypixel.hytale.codec.KeyedCodec;
import com.hypixel.hytale.codec.builder.BuilderCodec;
import com.hypixel.hytale.component.Ref;
import com.hypixel.hytale.component.Store;
import com.hypixel.hytale.protocol.packets.interface_.CustomPageLifetime;
import com.hypixel.hytale.protocol.packets.interface_.CustomUIEventBindingType;
import com.hypixel.hytale.server.core.entity.entities.Player;
import com.hypixel.hytale.server.core.entity.entities.player.pages.InteractiveCustomUIPage;
import com.hypixel.hytale.server.core.modules.entity.damage.DeathComponent;
import com.hypixel.hytale.server.core.ui.builder.EventData;
import com.hypixel.hytale.server.core.ui.builder.UICommandBuilder;
import com.hypixel.hytale.server.core.ui.builder.UIEventBuilder;
import com.hypixel.hytale.server.core.universe.PlayerRef;
import com.hypixel.hytale.server.core.universe.world.storage.EntityStore;
import net.haro0.hytale.graveprotocol.components.GPDeathComponent;
import net.haro0.hytale.graveprotocol.utils.DeathUtils;

import javax.annotation.Nonnull;

// Generated by Hytale UI Builder (https://hytale.ellie.au).
// You may edit this class as necessary, or copy parts only.
public class DeathDecisionUi extends InteractiveCustomUIPage<DeathDecisionUi.BindingData> {

    public DeathDecisionUi(@Nonnull PlayerRef playerRef) {

        super(playerRef, CustomPageLifetime.CantClose, BindingData.CODEC);
    }

    @Override
    public void build(@Nonnull Ref<EntityStore> ref, @Nonnull UICommandBuilder uiCommandBuilder, @Nonnull UIEventBuilder uiEventBuilder, @Nonnull Store<EntityStore> store) {

        uiCommandBuilder.append("Pages/DeathDecision.ui");

        uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#Normal", EventData.of("Action", "Normal"));
        uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#Custom", EventData.of("Action", "Custom"));

        // var config = MyPlugin.getInstance().config.get();

    }

    @Override
    public void handleDataEvent(@Nonnull Ref<EntityStore> ref, @Nonnull Store<EntityStore> store, @Nonnull BindingData data) {

        var player = store.getComponent(ref, Player.getComponentType());
        assert player != null;
        var decisionComponent = store.getComponent(ref, GPDeathComponent.getComponentType());
        assert decisionComponent != null;
        switch (data.action) {
            case "Normal" -> {
                store.putComponent(ref, DeathComponent.getComponentType(), decisionComponent.getOriginal());
            }
            case "Custom" -> {
                DeathUtils.moveToPrestigeInstance(ref, store);
                close();
            }
        }

    }

    public static class BindingData {

        public static final BuilderCodec<BindingData> CODEC = BuilderCodec.builder(BindingData.class, BindingData::new)
            .append(new KeyedCodec<>("Action", Codec.STRING), (entry, s) -> entry.action = s, entry -> entry.action).add()
            .build();

        private String action;

    }

}
